package eigatracker;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vennuss
 */
public class AddWindow extends javax.swing.JFrame {
    /**
     * Creates new form AddWindow
     */
    public AddWindow() {
        initComponents();
        mostrarSeries();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        MoviePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MovieName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MovieDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        MovieCheck = new javax.swing.JCheckBox();
        AddMovie = new javax.swing.JButton();
        SeriesPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SeriesName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SeriesDescription = new javax.swing.JTextArea();
        AddSeries = new javax.swing.JButton();
        ChapterPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ChapterCheck = new javax.swing.JCheckBox();
        ChapterNumber = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        ChapterSeason = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        SeriesTabla = new javax.swing.JTable();
        ChapterSearchBar = new javax.swing.JTextField();
        AddChapter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Window");
        setMinimumSize(new java.awt.Dimension(1100, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Name");

        MovieName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MovieName.setNextFocusableComponent(MovieCheck);
        MovieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieNameActionPerformed(evt);
            }
        });
        MovieName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MovieNameKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Description");

        MovieDescription.setColumns(20);
        MovieDescription.setRows(5);
        MovieDescription.setNextFocusableComponent(AddChapter);
        jScrollPane1.setViewportView(MovieDescription);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Have you seen this movie in a known lenguage?");

        MovieCheck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MovieCheck.setNextFocusableComponent(MovieDescription);

        AddMovie.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AddMovie.setText("ADD");
        AddMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MoviePanelLayout = new javax.swing.GroupLayout(MoviePanel);
        MoviePanel.setLayout(MoviePanelLayout);
        MoviePanelLayout.setHorizontalGroup(
            MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MoviePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MoviePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MoviePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MoviePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MovieName, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MovieCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MoviePanelLayout.setVerticalGroup(
            MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoviePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(MovieCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Movie", MoviePanel);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Name");

        SeriesName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SeriesName.setNextFocusableComponent(SeriesDescription);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Description");

        SeriesDescription.setColumns(20);
        SeriesDescription.setRows(5);
        SeriesDescription.setNextFocusableComponent(AddChapter);
        jScrollPane2.setViewportView(SeriesDescription);

        AddSeries.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AddSeries.setText("ADD");
        AddSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSeriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SeriesPanelLayout = new javax.swing.GroupLayout(SeriesPanel);
        SeriesPanel.setLayout(SeriesPanelLayout);
        SeriesPanelLayout.setHorizontalGroup(
            SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeriesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                    .addGroup(SeriesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SeriesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SeriesName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeriesPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        SeriesPanelLayout.setVerticalGroup(
            SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeriesPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(SeriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SeriesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Series", SeriesPanel);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Chapter");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Have you seen this chapter in a known lenguage?");

        ChapterCheck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ChapterCheck.setNextFocusableComponent(SeriesTabla);

        ChapterNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ChapterNumber.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        ChapterNumber.setName("ChapterNumber"); // NOI18N
        ChapterNumber.setNextFocusableComponent(ChapterSeason);
        ChapterNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChapterNumberMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Season");

        ChapterSeason.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ChapterSeason.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));
        ChapterSeason.setName("SeasonNumber"); // NOI18N
        ChapterSeason.setNextFocusableComponent(ChapterSearchBar);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Series");

        SeriesTabla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SeriesTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SeriesTabla.setNextFocusableComponent(AddChapter);
        SeriesTabla.setRowHeight(30);
        jScrollPane3.setViewportView(SeriesTabla);

        ChapterSearchBar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ChapterSearchBar.setNextFocusableComponent(ChapterCheck);
        ChapterSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ChapterSearchBarKeyTyped(evt);
            }
        });

        AddChapter.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AddChapter.setText("ADD");
        AddChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddChapterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChapterPanelLayout = new javax.swing.GroupLayout(ChapterPanel);
        ChapterPanel.setLayout(ChapterPanelLayout);
        ChapterPanelLayout.setHorizontalGroup(
            ChapterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChapterPanelLayout.createSequentialGroup()
                .addGroup(ChapterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChapterPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChapterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ChapterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ChapterPanelLayout.createSequentialGroup()
                                .addGroup(ChapterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ChapterPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ChapterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ChapterSeason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ChapterPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ChapterSearchBar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChapterCheck)
                                .addGap(0, 367, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        ChapterPanelLayout.setVerticalGroup(
            ChapterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChapterPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(ChapterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ChapterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ChapterSeason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ChapterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChapterCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(ChapterSearchBar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chapter", ChapterPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MovieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieNameActionPerformed

    private void MovieNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MovieNameKeyTyped
        
    }//GEN-LAST:event_MovieNameKeyTyped

    private void AddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMovieActionPerformed
        if(!MovieName.getText().isBlank()){
            BD bd = new BD();
            String sql = "insert into peliculas values('" + MovieName.getText() + "', '" + MovieDescription.getText() + "'," + MovieCheck.isSelected() + ");";
            bd.sentencia(sql);
            dispose();
        }else JOptionPane.showMessageDialog(rootPane, "Es necesario un nombre.");
    }//GEN-LAST:event_AddMovieActionPerformed

    private void AddSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSeriesActionPerformed
        if(!SeriesName.getText().isBlank()){
            BD bd = new BD();
            String sql = "insert into series values('" + SeriesName.getText() + "', '" + SeriesDescription.getText() + "');";
            bd.sentencia(sql);
            dispose();
        }else JOptionPane.showMessageDialog(rootPane, "Es necesario un nombre.");
    }//GEN-LAST:event_AddSeriesActionPerformed

    private void AddChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddChapterActionPerformed
        if(SeriesTabla.getSelectedRow() != -1){
            String serie = String.valueOf(SeriesTabla.getValueAt(SeriesTabla.getSelectedRow(), 0));
            BD bd = new BD();
            String sql = "insert into capitulos (capitulo, temporada, serie, conocida) values(" + ChapterNumber.getValue() + ", " + ChapterSeason.getValue() + ", '" + serie + "', " + ChapterCheck.isSelected() + ");";
            try{
                bd.sentencia(sql);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Error! " + ex.getMessage() + "\n" + ex.getCause());
            }
            dispose();
        }
    }//GEN-LAST:event_AddChapterActionPerformed

    private void ChapterSearchBarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ChapterSearchBarKeyTyped
        mostrarSeries();
    }//GEN-LAST:event_ChapterSearchBarKeyTyped

    private void ChapterNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChapterNumberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ChapterNumberMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddChapter;
    private javax.swing.JButton AddMovie;
    private javax.swing.JButton AddSeries;
    private javax.swing.JCheckBox ChapterCheck;
    private javax.swing.JSpinner ChapterNumber;
    private javax.swing.JPanel ChapterPanel;
    private javax.swing.JTextField ChapterSearchBar;
    private javax.swing.JSpinner ChapterSeason;
    private javax.swing.JCheckBox MovieCheck;
    private javax.swing.JTextArea MovieDescription;
    private javax.swing.JTextField MovieName;
    private javax.swing.JPanel MoviePanel;
    private javax.swing.JTextArea SeriesDescription;
    private javax.swing.JTextField SeriesName;
    private javax.swing.JPanel SeriesPanel;
    private javax.swing.JTable SeriesTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void mostrarSeries(){
        BD bd = new BD();
        DefaultTableModel tm = (DefaultTableModel) SeriesTabla.getModel();
        SeriesTabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tm.setRowCount(0);
        
        try {
            ResultSet rs1 = bd.consulta("select nombre from series where nombre like '%" + ChapterSearchBar.getText() + "%';");
            while (rs1.next()) {
                String nombre = rs1.getString("nombre"); 
                Object nuev[] = {nombre};
                tm.addRow(nuev);
            }
            bd.cerrarConexion();
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage() + "\n" + ex.getCause());
        }
    }
    
}
